[2022-06-20 16:40:29,535] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_first_dag.fetch_data_from_spotify manual__2022-06-20T14:39:37.517208+00:00 [queued]>
[2022-06-20 16:40:29,543] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_first_dag.fetch_data_from_spotify manual__2022-06-20T14:39:37.517208+00:00 [queued]>
[2022-06-20 16:40:29,543] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 16:40:29,543] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-06-20 16:40:29,544] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 16:40:29,562] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): fetch_data_from_spotify> on 2022-06-20 14:39:37.517208+00:00
[2022-06-20 16:40:29,565] {standard_task_runner.py:52} INFO - Started process 10904 to run task
[2022-06-20 16:40:29,569] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'fetch_data_from_spotify', 'manual__2022-06-20T14:39:37.517208+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpyl68ligk', '--error-file', '/tmp/tmppsa3j8r5']
[2022-06-20 16:40:29,570] {standard_task_runner.py:80} INFO - Job 89: Subtask fetch_data_from_spotify
[2022-06-20 16:40:29,623] {logging_mixin.py:109} INFO - Running <TaskInstance: my_first_dag.fetch_data_from_spotify manual__2022-06-20T14:39:37.517208+00:00 [running]> on host LAPTOP-M1F9EL62.localdomain
[2022-06-20 16:40:29,673] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=fetch_data_from_spotify
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T14:39:37.517208+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-20T14:39:37.517208+00:00
[2022-06-20 16:40:29,737] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/leizo/.local/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/leizo/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/leizo/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/leizo/airflow/dags/lib/spotify_fetcher.py", line 18, in fetch_data_from_spotify
    fetch_data_from_playlist(playlist, playlists_to_fetch[playlist])
  File "/home/leizo/airflow/dags/lib/spotify_fetcher.py", line 28, in fetch_data_from_playlist
    r = requests.get(url + 'playlists/' + id, headers=auth_to_spotify())
  File "/home/leizo/airflow/dags/lib/spotify_fetcher.py", line 46, in auth_to_spotify
    auth_response_data = auth_response.json()
  File "/home/leizo/.local/lib/python3.8/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] upstream connect error or disconnect/reset before headers. reset reason: connection termination: 0
[2022-06-20 16:40:29,750] {taskinstance.py:1278} INFO - Marking task as UP_FOR_RETRY. dag_id=my_first_dag, task_id=fetch_data_from_spotify, execution_date=20220620T143937, start_date=20220620T144029, end_date=20220620T144029
[2022-06-20 16:40:29,763] {standard_task_runner.py:93} ERROR - Failed to execute job 89 for task fetch_data_from_spotify ([Errno Expecting value] upstream connect error or disconnect/reset before headers. reset reason: connection termination: 0; 10904)
[2022-06-20 16:40:29,781] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-06-20 16:40:29,803] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
